export interface Customer {
  customer_id: string;
  customer_name: string;
  account_number: string;
  account_type: 'Savings' | 'Checking' | 'Premium' | 'Corporate';
  branch: string;
}

export interface Transaction {
  transaction_id: string;
  customer_id: string;
  amount: number;
  transaction_type: 'UPI' | 'NEFT' | 'RTGS' | 'IMPS' | 'ATM';
  beneficiary_status: 'Trusted' | 'New' | 'Suspicious';
  transaction_hour: number; // 0-23
  location: string;
  device_type: 'Mobile' | 'Desktop' | 'ATM' | 'Tablet';
  is_fraud: boolean;
}

export interface SecurityLog {
  customer_id: string;
  failed_login_attempts: number;
  new_device: boolean;
  ip_reputation: 'Safe' | 'Neutral' | 'Risky' | 'Malicious';
  vpn_detected: boolean;
  location_changed: boolean;
  multiple_sessions: boolean;
}

export interface QuantumThreatIndicator {
  node_id: string;
  protocol: string; // e.g. TLS 1.2, SSHv2, Kyber-1024
  encryption_strength: 'Vulnerable' | 'Highly Vulnerable' | 'Post-Quantum Safe';
  asymmetric_key_type: 'RSA-2048' | 'ECDSA-256' | 'Kyber-1024' | 'Dilithium-5';
  harvest_flag: boolean; // True = High probability of HNDL (Harvest-Now-Decrypt-Later) capture
  entropy_score: number; // 0.0 to 1.0 (Low entropy encrypted payloads indicate high packet structure, potential bulk ingestion)
  egress_size_gb: number; // High volume data egress
  threat_level: 'Low' | 'Medium' | 'High';
  last_intercept_timestamp: string;
}

export interface RiskAnalysis {
  customer_id: string;
  risk_score: number; // 0 to 100
  risk_level: 'Low' | 'Medium' | 'High';
  model_probability: number; // 0 to 1
  features: {
    score_from_telemetry: number;
    score_from_transaction: number;
    flagged_reasons: string[];
  };
  explanation: string; // Generated by Gemini
  recommendations: string[]; // Generated by Gemini
}

export interface DashboardStats {
  total_customers: number;
  total_transactions: number;
  fraud_count: number;
  average_risk_score: number;
  system_health: 'Optimal' | 'Degraded' | 'Critical';
  recent_transactions: (Transaction & { customer_name: string; risk_level: 'Low' | 'Medium' | 'High'; risk_score: number })[];
  quantum_indicators?: QuantumThreatIndicator[];
}

